--GROUP BY KULLANIMI


SELECT * FROM Kitap2

SELECT KitapYayýnEvi, COUNT(KitapAd) AS KÝTAP_SAYISI FROM Kitap2 GROUP BY KitapYayýnEvi

SELECT KitapAd, COUNT(KitapAd) AS SAYI FROM Kitap2 GROUP BY KitapAd

SELECT KitapFiyat, KitapYayýnEvi FROM Kitap2

SELECT KitapYayýnEvi, SUM(KitapFiyat) AS TOPLAM FROM Kitap2 GROUP BY KitapYayýnEvi ORDER BY KitapYayýnEvi DESC

SELECT KitapSayfa, KitapYayýnEvi FROM Kitap2

SELECT KitapYayýnEvi, MAX(KitapSayfa) AS MAKSÝMUM FROM Kitap2 GROUP BY KitapYayýnEvi

SELECT KitapFiyat, KitapYayýnEvi FROM Kitap2

SELECT KitapYayýnEvi, MIN(KitapFiyat) AS MÝNÝMUM FROM Kitap2 GROUP BY KitapYayýnEvi


SELECT * FROM Kiþiler

SELECT Meslek, COUNT(Ad) AS MESLEKLERE_GÖRE_PERSONEL_SAYISI FROM Kiþiler GROUP BY Meslek ORDER BY COUNT(Ad) DESC

SELECT * FROM Kiþiler

SELECT Þehir, COUNT(SoyAd) AS ÞEHÝRLERE_GÖRE_PERSONEL_SAYISI FROM Kiþiler GROUP BY Þehir ORDER BY COUNT(SoyAd) DESC

SELECT * FROM Kiþiler

SELECT Meslek, COUNT(Ad) AS MESLEKLERE_GÖRE_PERSONEL_SAYISI, SUM(Maaþ) AS MAAÞ_TOPLAMI FROM Kiþiler GROUP BY Meslek

SELECT * FROM Kiþiler

SELECT Þehir, COUNT(Ad) AS MESLEKLERE_GÖRE_PERSONEL_SAYISI, AVG(Maaþ) AS MAAÞ_ORTALAMASI FROM Kiþiler GROUP BY Þehir

SELECT * FROM Kiþiler

SELECT Meslek, COUNT(Ad) AS MESLEKLERE_GÖRE_PERSONEL_SAYISI, MAX(Maaþ) AS MAKSÝMUM, MIN(Maaþ) AS MÝNÝMUM FROM Kiþiler GROUP BY Meslek

SELECT * FROM Kiþiler

SELECT Þehir, COUNT(Ad) AS KÝÞÝ_SAYISI, SUM(MAAÞ) AS ÞEHÝRLERE_GÖRE_MAAÞ_TOPLAMI, SUM(Maaþ) * 1.30 AS ZAMLI_MAAÞ FROM Kiþiler GROUP BY Þehir 

SELECT * FROM Kiþiler

SELECT Þehir, COUNT(Meslek), SUM(Maaþ) AS MESLEK_SAYISI FROM Kiþiler GROUP BY Þehir, Meslek, Maaþ